apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: your_name_space
spec:
  ports:
  - name: web-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: web-https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: web
  type: LoadBalancer